// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibgopagxutjwauxtsmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZ29wYWd4dXRqd2F1eHRzbWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDMyNjgsImV4cCI6MjA2OTI3OTI2OH0.RVEqrU_jF0ruZuk2rQkN08LHJ2pQBbV_5WYx1JSbsxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});